set encoding=utf-8 fileencoding=

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" PLUGIN LIST
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'connorholyday/vim-snazzy'


call vundle#end()            " required
filetype plugin indent on    " required

syntax on
set colorcolumn=80
set number
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set mouse=a

colorscheme snazzy
